const ADMIN_HASH='2303978e62f60eab27127b6e69859912619e18414b2de31cdc2f39e5a35729a6';
const USER_HASH='bd4cddcd11537de6274924b06d5ed98ea7f3f24a34936a7e0e04d8361dff1757';
let db=JSON.parse(localStorage.getItem('das_db_v2')||'null');
if(!db){location.href='../';}
const $=s=>document.querySelector(s),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
function hash(v){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)).then(b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join(''))}
async function login(){const u=$('#user').value,p=$('#pass').value;if((await hash(u))!==USER_HASH||(await hash(p))!==ADMIN_HASH){$('#err').textContent='Invalid admin credentials';return}sessionStorage.setItem('das_admin','1');showAdmin()}
function logout(){sessionStorage.removeItem('das_admin');location.reload()}
function showLogin(){document.getElementById('login').innerHTML=`<div class="loginbox"><div class="login"><img src="../assets/logo/das-logo.jpg"><h2>Admin Login</h2><p class="muted">DAS ENTERPRISES management panel</p><div class="field"><label>Username</label><input id="user" autocomplete="username"></div><div class="field"><label>Password</label><input id="pass" type="password" autocomplete="current-password" onkeydown="if(event.key==='Enter')login()"></div><button class="btn" style="width:100%" onclick="login()">Login</button><p id="err" style="color:var(--danger)"></p><p class="muted" style="font-size:12px">GitHub Pages note: this demo login is client-side. For production, replace it with Supabase Auth + RLS.</p></div></div>`}
function showAdmin(){loginDiv.classList.add('hidden');admin.classList.remove('hidden');route()}
const loginDiv=document.getElementById('login'),admin=document.getElementById('admin'),V=document.getElementById('view');
function save(){localStorage.setItem('das_db_v2',JSON.stringify(db))}
function tableOrders(os){return `<table class="table"><tr><th>Order</th><th>Customer</th><th>Mobile</th><th>Amount</th><th>Status</th><th>Action</th></tr>${os.map(o=>`<tr><td><b>${o.id}</b><br><small>${new Date(o.createdAt).toLocaleString('en-IN')}</small></td><td>${o.customer}</td><td>${o.mobile}</td><td>${money(o.amount)}</td><td><span class="status">${o.status}</span></td><td><button class="btn" onclick="editOrder('${o.id}')">View / Edit</button></td></tr>`).join('')}</table>`}
function dashboard(){const sales=db.orders.reduce((s,o)=>s+o.amount,0),customers=new Set(db.orders.map(o=>o.mobile)).size;V.innerHTML=`<div class="topline"><h1>Dashboard</h1><a class="btn" href="../">Customer Site</a></div><div class="cards"><div class="card">Total Orders<div class="metric">${db.orders.length}</div></div><div class="card">Total Sales<div class="metric">${money(sales)}</div></div><div class="card">Customers<div class="metric">${customers}</div></div><div class="card">Products<div class="metric">${db.products.length}</div></div></div><div class="panel" style="margin-top:15px"><h2>Recent Orders</h2>${tableOrders(db.orders.slice(0,10))||'<p class="muted">No orders yet.</p>'}</div>`}
function products(){V.innerHTML=`<div class="topline"><h1>Products</h1><button class="btn" onclick="productForm()">+ Add Product</button></div><div class="panel"><table class="table"><tr><th>Image</th><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Action</th></tr>${db.products.map(p=>`<tr><td><img src="${p.image}" width="52" height="52"></td><td>${p.name}<br><small>${p.sku||''}</small></td><td>${p.category}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.active?'Active':'Inactive'}</td><td><button class="btn" onclick='productForm(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Edit</button> <button class="danger" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')}</table></div>`}
function productForm(p={}){V.innerHTML=`<h1>${p.id?'Edit':'Add'} Product</h1><div class="panel form"><input id="n" placeholder="Product Name" value="${p.name||''}"><input id="c" placeholder="Category" value="${p.category||'Necklace'}"><input id="pr" type="number" placeholder="Price" value="${p.price||''}"><input id="op" type="number" placeholder="Old Price" value="${p.oldPrice||''}"><input id="st" type="number" placeholder="Stock" value="${p.stock??''}"><input id="im" placeholder="Image path" value="${p.image||'./assets/jewellery/gold-ring-01.jpg'}"><input id="ma" placeholder="Material" value="${p.material||'Gold Plated'}"><input id="pu" placeholder="Purity" value="${p.purity||'18K Finish'}"><input id="we" placeholder="Weight" value="${p.weight||'10g'}"><input id="si" placeholder="Size" value="${p.size||'Free Size'}"><textarea id="de" placeholder="Description">${p.description||''}</textarea><label><input id="fe" type="checkbox" ${p.featured?'checked':''}> Featured</label><label><input id="ac" type="checkbox" ${p.active!==false?'checked':''}> Active</label><button class="btn" onclick="saveProduct('${p.id||''}')">Save Product</button></div>`}
function saveProduct(id){const old=db.products.find(x=>x.id===id)||{};const p={...old,id:id||'P'+Date.now(),name:n.value,category:c.value,price:+pr.value,oldPrice:+op.value,discount:op.value?Math.max(0,Math.round((1-(+pr.value/+op.value))*100)):0,stock:+st.value,image:im.value,material:ma.value,purity:pu.value,weight:we.value,size:si.value,description:de.value,featured:fe.checked,active:ac.checked,rating:old.rating||4.5,sku:old.sku||('DAS-'+Date.now().toString().slice(-5))};if(id)db.products=db.products.map(x=>x.id===id?p:x);else db.products.unshift(p);save();products()}
function deleteProduct(id){if(confirm('Delete this product?')){db.products=db.products.filter(x=>x.id!==id);save();products()}}
function orders(){V.innerHTML=`<div class="topline"><h1>Orders Management</h1><span class="muted">${db.orders.length} order(s)</span></div><div class="panel">${tableOrders(db.orders)}</div>`}
function editOrder(id){const o=db.orders.find(x=>x.id===id);V.innerHTML=`<div class="topline"><h1>Order ${o.id}</h1><button class="ghost" onclick="orders()">← Back</button></div><div class="grid"><div class="panel"><h3>Customer</h3><p><b>${o.customer}</b><br>${o.mobile}<br>${o.email||''}</p><p>${o.address}<br>${o.city||''}, ${o.state||''} ${o.pin||''}</p><h3>Payment</h3><p>${o.payment}</p></div><div class="panel"><h3>Order Items</h3>${o.items.map(x=>`<p>${x.name} × ${x.qty}<span style="float:right">${money(x.price*x.qty)}</span></p>`).join('')}<hr><p>Discount <span style="float:right">-${money(o.discount)}</span></p><p>Shipping <span style="float:right">${money(o.shipping)}</span></p><h3>Total <span style="float:right">${money(o.amount)}</span></h3><label>Status</label><select id="status" style="width:100%;margin:8px 0">${['Order Received','Confirmed','Processing','Packed','Shipped','Out for Delivery','Delivered','Cancelled','Returned'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select><button class="btn" onclick="updateOrder('${o.id}')">Update Status</button></div></div>`}
function updateOrder(id){const o=db.orders.find(x=>x.id===id);o.status=status.value;save();editOrder(id)}
function customers(){const map={};db.orders.forEach(o=>{const k=o.mobile;map[k]??={name:o.customer,mobile:o.mobile,email:o.email||'',orders:0,purchase:0,last:o.createdAt};map[k].orders++;map[k].purchase+=o.amount;if(o.createdAt>map[k].last)map[k].last=o.createdAt});const cs=Object.values(map);V.innerHTML=`<h1>Customers</h1><div class="panel"><table class="table"><tr><th>Name</th><th>Mobile</th><th>Email</th><th>Orders</th><th>Purchase</th><th>Last Order</th></tr>${cs.map(x=>`<tr><td>${x.name}</td><td>${x.mobile}</td><td>${x.email}</td><td>${x.orders}</td><td>${money(x.purchase)}</td><td>${new Date(x.last).toLocaleDateString('en-IN')}</td></tr>`).join('')}</table></div>`}
function offers(){V.innerHTML=`<div class="topline"><h1>Offers & Coupons</h1><button class="btn" onclick="addCoupon()">+ Create Coupon</button></div><div class="panel"><table class="table"><tr><th>Code</th><th>Type</th><th>Value</th><th>Minimum</th><th>Active</th><th>Action</th></tr>${db.coupons.map(x=>`<tr><td>${x.code}</td><td>${x.type}</td><td>${x.type==='percent'?x.value+'%':money(x.value)}</td><td>${money(x.minPurchase)}</td><td>${x.active?'Yes':'No'}</td><td><button class="btn" onclick="toggleCoupon('${x.code}')">${x.active?'Deactivate':'Activate'}</button> <button class="danger" onclick="deleteCoupon('${x.code}')">Delete</button></td></tr>`).join('')}</table></div>`}
function addCoupon(){const code=prompt('Coupon code');if(!code)return;const value=+prompt('Value','10'),type=prompt('Type: percent or fixed','percent'),minPurchase=+prompt('Minimum purchase','500');db.coupons.unshift({code:code.toUpperCase(),value,type,minPurchase,active:true});save();offers()}
function toggleCoupon(c){const x=db.coupons.find(x=>x.code===c);x.active=!x.active;save();offers()}function deleteCoupon(c){db.coupons=db.coupons.filter(x=>x.code!==c);save();offers()}
function banners(){V.innerHTML=`<div class="topline"><h1>Banners</h1><button class="btn" onclick="addBanner()">+ Add Banner</button></div><div class="grid">${db.banners.map(x=>`<div class="panel"><img src="${x.image}" style="width:100%;border-radius:9px"><h3>${x.title}</h3><p>${x.active?'Active':'Inactive'}</p><button class="btn" onclick="toggleBanner('${x.id}')">${x.active?'Deactivate':'Activate'}</button> <button class="danger" onclick="deleteBanner('${x.id}')">Delete</button></div>`).join('')}</div>`}
function addBanner(){const title=prompt('Banner title');if(!title)return;const image=prompt('Image path','./assets/banners/banner-01.jpg');db.banners.push({id:'B'+Date.now(),title,image,active:true});save();banners()}function toggleBanner(id){const x=db.banners.find(x=>x.id===id);x.active=!x.active;save();banners()}function deleteBanner(id){db.banners=db.banners.filter(x=>x.id!==id);save();banners()}
function reports(){const total=db.orders.reduce((s,o)=>s+o.amount,0),by={};db.orders.forEach(o=>by[o.status]=(by[o.status]||0)+1);V.innerHTML=`<h1>Reports & Analytics</h1><div class="cards"><div class="card">Total Sales<div class="metric">${money(total)}</div></div><div class="card">Total Orders<div class="metric">${db.orders.length}</div></div><div class="card">Delivered<div class="metric">${by.Delivered||0}</div></div><div class="card">Cancelled<div class="metric">${by.Cancelled||0}</div></div></div><div class="panel" style="margin-top:15px"><h2>Order Status Report</h2>${Object.entries(by).map(([k,v])=>`<p>${k}<b style="float:right">${v}</b></p>`).join('')||'<p class="muted">No orders yet.</p>'}</div>`}
function settings(){const s=db.settings;V.innerHTML=`<h1>Settings</h1><div class="panel form"><input id="wn" value="${s.websiteName||''}" placeholder="Website Name"><input id="cn" value="${s.contactNumber||''}" placeholder="Contact Number"><input id="em" value="${s.email||''}" placeholder="Email"><input id="ad" value="${s.address||''}" placeholder="Address"><input id="sh" type="number" value="${s.shippingCharge||0}" placeholder="Shipping Charge"><textarea id="rp">${s.returnPolicy||''}</textarea><button class="btn" onclick="saveSettings()">Save Changes</button></div>`}function saveSettings(){db.settings={...db.settings,websiteName:wn.value,contactNumber:cn.value,email:em.value,address:ad.value,shippingCharge:+sh.value,returnPolicy:rp.value};save();alert('Settings saved')}
function toggleAdminTheme(){document.body.classList.toggle('dark');localStorage.setItem('das_admin_dark',document.body.classList.contains('dark')?'1':'0')}
function route(){const r=location.hash.slice(1)||'dashboard';({dashboard,products,orders,customers,offers,banners,reports,settings}[r]||dashboard)()}
addEventListener('hashchange',route);
if(sessionStorage.getItem('das_admin')==='1')showAdmin();else showLogin();
if(localStorage.getItem('das_admin_dark')==='1')document.body.classList.add('dark');
