(function(){'use strict';
const KEY='das-enterprises-state-v2';
const states=['Order Received','Confirmed','Processing','Packed','Shipped','Out for Delivery','Delivered','Cancelled','Returned'];
function load(){try{return JSON.parse(localStorage.getItem(KEY))||null}catch(e){return null}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
let state=load();
function requireState(){if(!state){document.getElementById('adminApp').innerHTML='<div class="login"><div class="loginbox panel"><h1>Customer site not initialized</h1><p>Open the customer home page once, then return to Admin.</p><a class="btn" href="../">Open Customer Site</a></div></div>';throw Error('no state')}}
function shell(view='dashboard'){requireState();const nav=[['dashboard','Dashboard'],['products','Products'],['orders','Orders'],['customers','Customers'],['offers','Offers'],['banners','Banners'],['reviews','Reviews'],['reports','Reports'],['settings','Settings']];document.getElementById('adminApp').innerHTML=`<div class="admin-shell"><aside class="sidebar"><div class="logo"><img src="../assets/logo/das-logo.jpg"><span>DAS ENTERPRISES</span></div>${nav.map(([k,t])=>`<a class="side-link ${view===k?'active':''}" href="#${k}">${t}</a>`).join('')}<hr><a class="side-link" href="../">← Customer Site</a><button class="side-link" style="border:0;background:none;width:100%;text-align:left" onclick="window.Admin.theme()">☾ / ☀ Theme</button></aside><main class="main"><div class="topbar"><h1>${nav.find(x=>x[0]===view)?.[1]||'Admin'}</h1><span class="muted">Static Admin UI · Supabase-ready</span></div><div id="view"></div></main></div>`;return document.getElementById('view')}
function dashboard(){const v=shell('dashboard'),orders=state.orders,sales=orders.reduce((a,o)=>a+o.amount,0);const counts={};orders.forEach(o=>counts[o.status]=(counts[o.status]||0)+1);v.innerHTML=`<div class="grid4"><div class="card">Total Orders<div class="metric">${orders.length}</div></div><div class="card">Total Sales<div class="metric">${money(sales)}</div></div><div class="card">Customers<div class="metric">${state.customers.length}</div></div><div class="card">Products<div class="metric">${state.products.length}</div></div></div><div class="grid2" style="margin-top:15px"><div class="panel"><h2>Sales Overview</h2><p class="muted">Orders stored on this browser.</p><div class="chartbar">${[0,1,2,3,4,5,6].map((_,i)=>{const val=orders.filter(o=>new Date(o.createdAt).getDay()===i).reduce((a,o)=>a+o.amount,0);return `<span title="${money(val)}" style="height:${Math.max(8,Math.min(100,val/(sales||1)*100))}%"></span>`}).join('')}</div></div><div class="panel"><h2>Order Status</h2>${states.map(s=>`<p>${s}<b style="float:right">${counts[s]||0}</b></p>`).join('')}</div></div><div class="panel" style="margin-top:15px"><div class="bar"><h2>Recent Orders</h2><a class="btn" href="#orders">View All</a></div>${orderTable(orders.slice().reverse().slice(0,8))}</div>`}
function orderTable(os){return `<div class="tablewrap"><table><tr><th>Order</th><th>Customer</th><th>Amount</th><th>Payment</th><th>Status</th><th>Action</th></tr>${os.map(o=>`<tr><td>${esc(o.id)}<br><small class="muted">${esc(o.createdAt)}</small></td><td>${esc(o.customer)}<br><small>${esc(o.mobile)}</small></td><td>${money(o.amount)}</td><td>${esc(o.payment)}</td><td><span class="status">${esc(o.status)}</span></td><td><button class="btn secondary" onclick="window.Admin.order('${o.id}')">View</button></td></tr>`).join('')||'<tr><td colspan="6">No orders yet.</td></tr>'}</table></div>`}
function products(){const v=shell('products');v.innerHTML=`<div class="bar"><input class="search" id="psearch" placeholder="Search products" oninput="window.Admin.filterProducts()"><button class="btn" onclick="window.Admin.productForm()">+ Add Product</button></div><div class="panel tablewrap" id="ptable"></div>`;renderProducts()}
function renderProducts(){const el=document.getElementById('ptable');if(!el)return;const q=(document.getElementById('psearch')?.value||'').toLowerCase();const ps=state.products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q));el.innerHTML=`<table><tr><th>Image</th><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr>${ps.map(p=>`<tr><td><img src="../${p.image.replace(/^\.\//,'')}"></td><td><b>${esc(p.name)}</b><br><small>${esc(p.id)}</small></td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.active!==false?'Active':'Inactive'}</td><td class="actions"><button class="btn secondary" onclick="window.Admin.productForm('${p.id}')">Edit</button><button class="btn danger" onclick="window.Admin.deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')}</table>`}
function productForm(id=''){const p=state.products.find(x=>x.id===id)||{id:'',name:'',category:'Ring',price:0,oldPrice:0,discount:0,stock:0,rating:4.5,material:'Gold Plated',purity:'18K Finish',weight:'',size:'Free Size',image:'./assets/jewellery/gold-ring-01.jpg',description:'',featured:false,active:true};const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="panel"><div class="bar"><h2>${id?'Edit':'Add'} Product</h2><button class="btn secondary" onclick="this.closest('.modal').remove()">Close</button></div><div class="formgrid">${field('Name','fName',p.name)}${field('Category','fCategory',p.category)}${field('Price','fPrice',p.price,'number')}${field('Old Price','fOld',p.oldPrice,'number')}${field('Discount %','fDisc',p.discount,'number')}${field('Stock','fStock',p.stock,'number')}${field('Image path','fImage',p.image)}${field('Material','fMaterial',p.material)}${field('Purity','fPurity',p.purity)}${field('Weight','fWeight',p.weight)}${field('Size','fSize',p.size)}${field('Rating','fRating',p.rating,'number')}</div><div class="field"><label>Description</label><textarea id="fDesc">${esc(p.description)}</textarea></div><label><input id="fFeatured" type="checkbox" ${p.featured?'checked':''}> Featured</label><label><input id="fActive" type="checkbox" ${p.active!==false?'checked':''}> Active</label><button class="btn" onclick="window.Admin.saveProduct('${id}')">Save Product</button></div>`;document.body.appendChild(m)}
function field(label,id,value,type='text'){return `<div class="field"><label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label></div>`}
function saveProduct(id){const p=state.products.find(x=>x.id===id)||{id:'P'+Date.now()};Object.assign(p,{name:fName.value.trim(),category:fCategory.value.trim(),price:+fPrice.value,oldPrice:+fOld.value,discount:+fDisc.value,stock:+fStock.value,image:fImage.value.trim(),material:fMaterial.value.trim(),purity:fPurity.value.trim(),weight:fWeight.value.trim(),size:fSize.value.trim(),rating:+fRating.value,description:fDesc.value,featured:fFeatured.checked,active:fActive.checked});if(!id)state.products.push(p);save(state);document.querySelector('.modal')?.remove();products();toast('Product saved')}
function deleteProduct(id){if(!confirm('Delete product?'))return;state.products=state.products.filter(p=>p.id!==id);save(state);products();toast('Deleted')}
function orders(){const v=shell('orders');v.innerHTML=`<div class="chips">${['All',...states].map(s=>`<button class="btn secondary" onclick="window.Admin.filterOrders('${s}')">${s}</button>`).join('')}</div><div class="panel" id="otable">${orderTable(state.orders.slice().reverse())}</div>`}
function filterOrders(status){const list=status==='All'?state.orders:state.orders.filter(o=>o.status===status);document.getElementById('otable').innerHTML=orderTable(list.slice().reverse())}
function order(id){const o=state.orders.find(x=>x.id===id);if(!o)return;const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="panel"><div class="bar"><h2>${esc(o.id)}</h2><button class="btn secondary" onclick="this.closest('.modal').remove()">Close</button></div><p><b>${esc(o.customer)}</b> · ${esc(o.mobile)} · ${esc(o.email)}</p><p>${esc(o.address)}, ${esc(o.city)}, ${esc(o.state)} - ${esc(o.pin)}</p><h3>Items</h3>${o.items.map(i=>`<p>${esc(i.name)} × ${i.qty} <b style="float:right">${money(i.price*i.qty)}</b></p>`).join('')}<hr><p>Subtotal <b style="float:right">${money(o.subtotal)}</b></p><p>Shipping <b style="float:right">${money(o.shipping)}</b></p><p>Discount <b style="float:right">-${money(o.discount)}</b></p><h2>Total <b style="float:right">${money(o.amount)}</b></h2><label>Status<select id="orderStatus">${states.map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></label><button class="btn" onclick="window.Admin.updateOrder('${o.id}')">Update Status</button></div>`;document.body.appendChild(m)}
function updateOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;o.status=document.getElementById('orderStatus').value;o.history=o.history||[];o.history.push({status:o.status,at:new Date().toLocaleString('en-IN')});save(state);document.querySelector('.modal')?.remove();orders();toast('Order status updated')}
function customers(){const v=shell('customers');v.innerHTML=`<div class="panel tablewrap"><table><tr><th>Name</th><th>Mobile</th><th>Email</th><th>Orders</th><th>Purchase</th><th>Last Order</th></tr>${state.customers.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.mobile)}</td><td>${esc(c.email)}</td><td>${c.totalOrders}</td><td>${money(c.totalPurchase)}</td><td>${esc(c.lastOrder)}</td></tr>`).join('')||'<tr><td colspan="6">Customers appear here after orders are placed.</td></tr>'}</table></div>`}
function offers(){const v=shell('offers');v.innerHTML=`<div class="bar"><h2>Coupons</h2><button class="btn" onclick="window.Admin.addCoupon()">+ Create Coupon</button></div><div class="panel tablewrap"><table><tr><th>Code</th><th>Type</th><th>Value</th><th>Minimum</th><th>Status</th><th>Action</th></tr>${state.coupons.map(c=>`<tr><td><b>${esc(c.code)}</b></td><td>${c.type}</td><td>${c.type==='percent'?c.value+'%':money(c.value)}</td><td>${money(c.minPurchase)}</td><td>${c.active?'Active':'Inactive'}</td><td><button class="btn secondary" onclick="window.Admin.toggleCoupon('${esc(c.code)}')">Toggle</button> <button class="btn danger" onclick="window.Admin.deleteCoupon('${esc(c.code)}')">Delete</button></td></tr>`).join('')}</table></div>`}
function addCoupon(){const code=prompt('Coupon code');if(!code)return;const value=+prompt('Value','10');const type=prompt('Type: percent or fixed','percent');const min=+prompt('Minimum purchase','1000');state.coupons.push({code:code.toUpperCase(),value,type:type==='fixed'?'fixed':'percent',minPurchase:min,active:true});save(state);offers()}
function toggleCoupon(code){const c=state.coupons.find(x=>x.code===code);if(c)c.active=!c.active;save(state);offers()}
function deleteCoupon(code){state.coupons=state.coupons.filter(x=>x.code!==code);save(state);offers()}
function banners(){const v=shell('banners');v.innerHTML=`<div class="bar"><h2>Home Banners</h2><button class="btn" onclick="window.Admin.addBanner()">+ Add Banner</button></div><div class="grid2">${state.banners.map(b=>`<div class="panel"><img src="../${b.image.replace(/^\.\//,'')}" style="width:100%;height:180px;object-fit:cover;border-radius:10px"><h3>${esc(b.title)}</h3><p class="muted">${esc(b.subtitle)}</p><div class="actions"><button class="btn secondary" onclick="window.Admin.toggleBanner('${b.id}')">${b.active?'Deactivate':'Activate'}</button><button class="btn danger" onclick="window.Admin.deleteBanner('${b.id}')">Delete</button></div></div>`).join('')}</div>`}
function addBanner(){const title=prompt('Banner title');if(!title)return;const image=prompt('Image path','./assets/banners/banner-01.jpg');const subtitle=prompt('Subtitle','Premium jewellery for every moment.');state.banners.push({id:'B'+Date.now(),title,subtitle,image,active:true});save(state);banners()}
function toggleBanner(id){const b=state.banners.find(x=>x.id===id);if(b)b.active=!b.active;save(state);banners()}
function deleteBanner(id){state.banners=state.banners.filter(x=>x.id!==id);save(state);banners()}
function reviews(){const v=shell('reviews');v.innerHTML=`<div class="panel tablewrap"><table><tr><th>Customer</th><th>Product</th><th>Rating</th><th>Review</th><th>Status</th><th>Action</th></tr>${state.reviews.map(r=>`<tr><td>${esc(r.customer)}</td><td>${esc(state.products.find(p=>p.id===r.productId)?.name||r.productId)}</td><td>★${r.rating}</td><td>${esc(r.review)}</td><td>${esc(r.status)}</td><td><button class="btn secondary" onclick="window.Admin.reviewStatus('${r.id}','Approved')">Approve</button> <button class="btn danger" onclick="window.Admin.reviewStatus('${r.id}','Hidden')">Hide</button></td></tr>`).join('')}</table></div>`}
function reviewStatus(id,s){const r=state.reviews.find(x=>x.id===id);if(r)r.status=s;save(state);reviews()}
function reports(){const v=shell('reports');const sales=state.orders.reduce((a,o)=>a+o.amount,0),del=state.orders.filter(o=>o.status==='Delivered').length,cancel=state.orders.filter(o=>o.status==='Cancelled').length;v.innerHTML=`<div class="grid4"><div class="card">Sales<div class="metric">${money(sales)}</div></div><div class="card">Orders<div class="metric">${state.orders.length}</div></div><div class="card">Delivered<div class="metric">${del}</div></div><div class="card">Cancelled<div class="metric">${cancel}</div></div></div><div class="grid2" style="margin-top:15px"><div class="panel"><h2>Category Sales</h2>${state.products.map(p=>{const qty=state.orders.reduce((a,o)=>a+(o.items.find(i=>i.productId===p.id)?.qty||0),0);return `<p>${esc(p.name)}<b style="float:right">${qty}</b></p>`}).join('')}</div><div class="panel"><h2>Inventory</h2>${state.products.map(p=>`<p>${esc(p.name)}<b style="float:right">${p.stock}</b></p>`).join('')}</div></div>`}
function settings(){const v=shell('settings'),s=state.settings;v.innerHTML=`<div class="panel"><div class="formgrid">${field('Website Name','sName',s.websiteName)}${field('Contact Number','sPhone',s.contactNumber)}${field('Email','sEmail',s.email)}${field('Address','sAddress',s.address)}${field('Shipping Charge','sShip',s.shippingCharge,'number')}${field('Free Shipping Above','sFree',s.freeShippingAbove,'number')}</div><div class="field"><label>Return Policy<textarea id="sReturn">${esc(s.returnPolicy)}</textarea></label></div><button class="btn" onclick="window.Admin.saveSettings()">Save Settings</button></div><div class="notice" style="margin-top:15px"><b>Production security:</b> this GitHub Pages build intentionally does not store an admin password in frontend code. Connect Supabase Auth + RLS before using this as a real public admin system.</div>`}
function saveSettings(){state.settings={websiteName:sName.value,contactNumber:sPhone.value,email:sEmail.value,address:sAddress.value,shippingCharge:+sShip.value,freeShippingAbove:+sFree.value,returnPolicy:sReturn.value};save(state);toast('Settings saved')}
function theme(){const d=document.body.classList.toggle('dark');localStorage.setItem('das-admin-theme',d?'dark':'light')}
if(localStorage.getItem('das-admin-theme')==='dark')document.body.classList.add('dark');
function route(){const k=location.hash.slice(1)||'dashboard';({dashboard,products,orders,customers,offers,banners,reviews,reports,settings}[k]||dashboard)()}
window.Admin={theme,filterProducts:renderProducts,productForm,saveProduct,deleteProduct,order,updateOrder,filterOrders,addCoupon,toggleCoupon,deleteCoupon,addBanner,toggleBanner,deleteBanner,reviewStatus,saveSettings};addEventListener('hashchange',route);route();
})();
