/* DAS ENTERPRISES - GitHub Pages customer app
   Static build: data is persisted in localStorage so customer/admin UI can work on the same browser.
   For production, replace the storage adapter with Supabase Auth/DB/RLS. */
(function(){
  'use strict';
  const KEY='das-enterprises-state-v3';
  const seed={
    products:[
      {id:'P001',name:'Classic Gold Ring',category:'Ring',price:2499,oldPrice:3499,discount:29,stock:14,rating:4.8,material:'Gold Plated',purity:'18K Finish',weight:'4.2g',size:'Adjustable',image:'https://i.ibb.co/YB3945mL/image-364f5a8.jpg',description:'Elegant everyday ring with a premium polished finish.',featured:true,active:true},
      {id:'P002',name:'Royal Gold Necklace',category:'Necklace',price:6499,oldPrice:8999,discount:28,stock:8,rating:4.7,material:'Gold Plated',purity:'22K Finish',weight:'18g',size:'Free Size',image:'https://i.ibb.co/PZPYr6WD/image-c9217abf.jpg',description:'Statement necklace designed for festive and wedding looks.',featured:true,active:true},
      {id:'P003',name:'Pearl Drop Earrings',category:'Earrings',price:1799,oldPrice:2499,discount:28,stock:22,rating:4.6,material:'Alloy',purity:'Premium Finish',weight:'5g',size:'Medium',image:'https://i.ibb.co/Txh5DGGb/image-77b0d76d.jpg',description:'Lightweight pearl-inspired earrings for daily elegance.',featured:true,active:true},
      {id:'P004',name:'Temple Necklace Set',category:'Necklace',price:5299,oldPrice:6999,discount:24,stock:6,rating:4.8,material:'Gold Plated',purity:'22K Finish',weight:'20g',size:'Free Size',image:'https://i.ibb.co/PZPYr6WD/image-c9217abf.jpg',description:'Traditional-inspired necklace set with intricate detailing.',featured:false,active:true},
      {id:'P005',name:'Black Bead Mangalsutra',category:'Mangalsutra',price:2999,oldPrice:3999,discount:25,stock:11,rating:4.7,material:'Gold Plated',purity:'18K Finish',weight:'8g',size:'Adjustable',image:'./assets/products/das-anklet-01.jpg',description:'Classic mangalsutra style for timeless everyday wear.',featured:true,active:true},
      {id:'P006',name:'Classic Gold Bangles',category:'Bangles',price:3599,oldPrice:4999,discount:28,stock:9,rating:4.5,material:'Gold Plated',purity:'18K Finish',weight:'12g',size:'2.4',image:'https://i.ibb.co/PZPYr6WD/image-c9217abf.jpg',description:'Pair of versatile bangles with a clean polished look.',featured:false,active:true},
      {id:'P007',name:'Crystal Gold Ring',category:'Ring',price:2199,oldPrice:2999,discount:27,stock:17,rating:4.6,material:'Gold Plated',purity:'18K Finish',weight:'3.8g',size:'Adjustable',image:'https://i.ibb.co/YB3945mL/image-364f5a8.jpg',description:'Minimal crystal ring for gifting and special occasions.',featured:false,active:true},
      {id:'P008',name:'Charm Bracelet',category:'Bracelet',price:1899,oldPrice:2699,discount:30,stock:19,rating:4.7,material:'Alloy',purity:'Premium Finish',weight:'7g',size:'Adjustable',image:'https://i.ibb.co/PZPYr6WD/image-c9217abf.jpg',description:'Delicate charm bracelet with a polished finish.',featured:true,active:true},
      {id:'P009',name:'Silver Anklet Pair',category:'Anklet',price:1299,oldPrice:1699,discount:24,stock:15,rating:4.4,material:'Silver Finish',purity:'925 Style',weight:'14g',size:'Free Size',image:'./assets/products/das-anklet-01.jpg',description:'Graceful anklet pair for everyday and festive wear.',featured:false,active:true},
      {id:'P010',name:'Premium Gift Set',category:'Gift',price:3999,oldPrice:5499,discount:27,stock:7,rating:4.9,material:'Mixed Jewellery',purity:'Premium Finish',weight:'16g',size:'Free Size',image:'https://i.ibb.co/YB3945mL/image-364f5a8.jpg',description:'Curated jewellery gift set for birthdays, anniversaries and festivals.',featured:true,active:true}
    ],
    banners:[
      {id:'B001',title:'Luxury In Every Detail',subtitle:'Premium jewellery for memorable moments.',image:'./assets/banners/banner-01.jpg',active:true},
      {id:'B002',title:'Celebrate With Elegance',subtitle:'New festive styles are here.',image:'./assets/banners/banner-02.jpg',active:true},
      {id:'B003',title:'Gifts That Shine',subtitle:'Thoughtful jewellery for every occasion.',image:'./assets/banners/banner-03.jpg',active:true}
    ],
    coupons:[{code:'WELCOME10',type:'percent',value:10,minPurchase:1000,active:true},{code:'SAVE500',type:'fixed',value:500,minPurchase:3000,active:true}],
    orders:[],customers:[],reviews:[
      {id:'R001',customer:'Demo Customer',productId:'P001',rating:5,review:'Beautiful finish and packaging.',status:'Approved',date:'2026-09-10'},
      {id:'R002',customer:'Demo Customer',productId:'P002',rating:4,review:'Looks premium and arrived safely.',status:'Approved',date:'2026-09-12'}
    ],settings:{websiteName:'DAS ENTERPRISES',contactNumber:'+91 90000 00000',email:'support@dasenterprises.example',address:'West Bengal, India',shippingCharge:100,freeShippingAbove:1500,returnPolicy:'7 Days Return'}
  };
  const clone=o=>JSON.parse(JSON.stringify(o));
  let state=load();
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&x.products?x:clone(seed)}catch(e){return clone(seed)}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function money(n){return '₹'+Number(n||0).toLocaleString('en-IN')}
  function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function cart(){return JSON.parse(localStorage.getItem('das-cart')||'[]')}
  function wish(){return JSON.parse(localStorage.getItem('das-wish')||'[]')}
  function setCart(x){localStorage.setItem('das-cart',JSON.stringify(x))}
  function setWish(x){localStorage.setItem('das-wish',JSON.stringify(x))}
  function countCart(){return cart().reduce((a,x)=>a+x.qty,0)}
  function categories(){return ['Gold Jewellery','Silver Jewellery','Ring','Earrings','Necklace','Bangles','Bracelet','Anklet','Mangalsutra','Gift','Offers']}
  function activeProducts(){return state.products.filter(p=>p.active!==false)}
  function layout(content,opts={}){
    const q=esc(opts.q||'');
    document.getElementById('app').innerHTML=`<header class="site-header"><div class="container navrow">
      <a class="brand" href="#home"><img src="https://i.ibb.co/LhR9HTTX/das-logo.jpg" alt="DAS ENTERPRISES"><span>DAS ENTERPRISES</span></a>
      <button class="mobile-menu" onclick="window.DAS.toggleMenu()">☰</button>
      <div class="search"><input id="searchBox" value="${q}" placeholder="Search jewellery..."><button onclick="window.DAS.search()">⌕</button></div>
      <nav id="mainNav"><a href="#home">Home</a><a href="#shop">Categories</a><a href="#offers">Offers</a><a href="#wishlist">♥ Wishlist</a><a href="#account">Account</a><a href="#cart">🛒 Cart <b id="cartCount">${countCart()}</b></a><a class="admin-link" href="./admin/">Admin</a><button class="theme" onclick="window.DAS.theme()">☾ / ☀</button></nav>
    </div></header>${content}<footer><div class="container footergrid"><div><h3>DAS ENTERPRISES</h3><p>Jewellery for a Better Tomorrow.</p></div><div><h4>Shop</h4><a href="#shop">All Jewellery</a><a href="#offers">Offers</a><a href="#wishlist">Wishlist</a></div><div><h4>Support</h4><p>7 Days Return</p><p>Secure Checkout</p></div><div><h4>Contact</h4><p>${esc(state.settings.contactNumber)}</p><p>${esc(state.settings.email)}</p></div></div><div class="copyright">© ${new Date().getFullYear()} DAS ENTERPRISES</div></footer>`;
    document.documentElement.dataset.theme=localStorage.getItem('das-theme')||'light';
  }
  function productCard(p){const w=wish().includes(p.id);return `<article class="product-card"><a href="#product/${encodeURIComponent(p.id)}"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"></a><div class="product-info"><div class="tag">${esc(p.category)}</div><a href="#product/${encodeURIComponent(p.id)}"><h3>${esc(p.name)}</h3></a><div><span class="price">${money(p.price)}</span> <del>${money(p.oldPrice)}</del> <span class="discount">${p.discount}% OFF</span></div><div class="rating">★ ${p.rating||4.5} · ${p.stock} in stock</div><div class="card-actions"><button class="iconbtn ${w?'active':''}" onclick="window.DAS.wish('${p.id}');return false">♥</button><button class="primary" onclick="window.DAS.add('${p.id}');return false">Add to Cart</button><button class="outline" onclick="window.DAS.buy('${p.id}');return false">Buy Now</button></div></div></article>`}
  function home(){const b=state.banners.find(x=>x.active)||state.banners[0];const ps=activeProducts();layout(`<main><section class="hero container"><img src="${esc(b?.image||'./assets/banners/banner-01.jpg')}" alt="Jewellery banner"><div class="hero-copy"><span>PREMIUM JEWELLERY</span><h1>${esc(b?.title||'Luxury In Every Detail')}</h1><p>${esc(b?.subtitle||'Premium jewellery designed to make every moment memorable.')}</p><a class="primary big" href="#shop">Shop Now</a></div></section><section class="container section"><div class="sectionhead"><div><span class="eyebrow">EXPLORE</span><h2>Shop by Category</h2></div><a href="#shop">View All →</a></div><div class="category-grid">${categories().slice(0,8).map((c,i)=>`<a href="#cat/${encodeURIComponent(c)}" class="category-card"><img src="${esc(ps[i%ps.length]?.image||'./assets/products/das-rings-01.jpg')}" alt="${esc(c)}"><span>${esc(c)}</span></a>`).join('')}</div></section><section class="container section"><div class="sectionhead"><div><span class="eyebrow">HANDPICKED</span><h2>Featured Jewellery</h2></div><a href="#shop">Shop Collection →</a></div><div class="product-grid">${ps.filter(p=>p.featured).slice(0,8).map(productCard).join('')}</div></section><section id="offers" class="container section offer-strip"><div><span class="eyebrow">LIMITED TIME</span><h2>Special Offers</h2><p>Save on selected jewellery styles with active coupons.</p></div><a class="primary" href="#offers-page">View Offers</a></section></main>`)
  }
  function shop(category='All',query=''){let ps=activeProducts();if(category==='Offers')ps=ps.filter(p=>p.discount>=20);else if(category!=='All'&&category!=='Gold Jewellery'&&category!=='Silver Jewellery')ps=ps.filter(p=>p.category.toLowerCase()===category.toLowerCase());else if(category==='Gold Jewellery')ps=ps.filter(p=>/gold|ring|necklace|bangle|bracelet|mangalsutra/i.test(p.category+' '+p.material));else if(category==='Silver Jewellery')ps=ps.filter(p=>/silver/i.test(p.material));if(query)ps=ps.filter(p=>(p.name+' '+p.category+' '+p.description).toLowerCase().includes(query.toLowerCase()));layout(`<main class="container section"><div class="sectionhead"><div><span class="eyebrow">COLLECTION</span><h1>Jewellery Collection</h1><p>${query?'Search results for “'+esc(query)+'”':''}</p></div><select onchange="window.DAS.cat(this.value)"><option>All</option>${categories().map(c=>`<option ${c===category?'selected':''}>${esc(c)}</option>`).join('')}</select></div><div class="chips">${categories().map(c=>`<button class="chip ${c===category?'selected':''}" onclick="window.DAS.cat('${c}')">${esc(c)}</button>`).join('')}</div><div class="product-grid">${ps.length?ps.map(productCard).join(''):'<div class="empty panel"><h3>No products found</h3><a href="#shop">Clear filters</a></div>'}</div></main>`,{q:query})}
  function product(id){const p=state.products.find(x=>x.id===id);if(!p){return notFound()}layout(`<main class="container section"><button class="back" onclick="history.back()">← Back</button><div class="product-detail"><div class="detail-image panel"><img src="${esc(p.image)}" alt="${esc(p.name)}"></div><div class="detail-info"><div class="tag">${esc(p.category)}</div><h1>${esc(p.name)}</h1><div class="rating bigrating">★ ${p.rating||4.5} <span>Customer rating</span></div><div class="detail-price"><b>${money(p.price)}</b><del>${money(p.oldPrice)}</del><span class="discount">${p.discount}% OFF</span></div><p>${esc(p.description)}</p><div class="specgrid"><div><b>Material</b><span>${esc(p.material)}</span></div><div><b>Purity</b><span>${esc(p.purity)}</span></div><div><b>Weight</b><span>${esc(p.weight)}</span></div><div><b>Size</b><span>${esc(p.size)}</span></div></div><div class="stock">${p.stock>0?'✓ In stock':'Out of stock'} · Delivery 3–7 Days · 7 Days Return</div><div class="qty"><button onclick="window.DAS.qty(-1)">−</button><input id="detailQty" value="1" min="1" max="${p.stock}" type="number"><button onclick="window.DAS.qty(1)">+</button></div><div class="detail-actions"><button class="primary big" onclick="window.DAS.add('${p.id}',Number(document.getElementById('detailQty').value||1))">Add to Cart</button><button class="outline big" onclick="window.DAS.buy('${p.id}')">Buy Now</button><button class="iconbtn large ${wish().includes(p.id)?'active':''}" onclick="window.DAS.wish('${p.id}')">♥</button></div></div></div><div class="tabs panel"><h2>Specifications & Reviews</h2><p>Premium finish, carefully packed for safe delivery. Customer reviews are shown after approval.</p>${state.reviews.filter(r=>r.productId===p.id&&r.status==='Approved').map(r=>`<div class="review"><b>${esc(r.customer)}</b> · ★${r.rating}<p>${esc(r.review)}</p></div>`).join('')||'<p class="muted">No reviews yet.</p>'}</div></main>`)}
  function cartPage(){const c=cart();const rows=c.map(i=>({i,p:state.products.find(p=>p.id===i.productId)})).filter(x=>x.p);const sub=rows.reduce((s,x)=>s+x.p.price*x.i.qty,0);const ship=sub?(sub>=state.settings.freeShippingAbove?0:state.settings.shippingCharge):0;layout(`<main class="container section"><div class="sectionhead"><div><span class="eyebrow">YOUR BAG</span><h1>Shopping Cart</h1></div></div>${rows.length?`<div class="cart-layout"><div class="panel">${rows.map(x=>`<div class="cart-row"><img src="${esc(x.p.image)}"><div class="grow"><h3>${esc(x.p.name)}</h3><p>${money(x.p.price)} · ${esc(x.p.category)}</p><div class="qty"><button onclick="window.DAS.change('${x.p.id}',-1)">−</button><span>${x.i.qty}</span><button onclick="window.DAS.change('${x.p.id}',1)">+</button><button class="linkdanger" onclick="window.DAS.remove('${x.p.id}')">Remove</button></div></div><b>${money(x.p.price*x.i.qty)}</b></div>`).join('')}</div><aside class="panel summary"><h2>Order Summary</h2><p>Subtotal <b>${money(sub)}</b></p><p>Delivery <b>${ship?money(ship):'FREE'}</b></p><hr><h2>Total <b>${money(sub+ship)}</b></h2><a class="primary big full" href="#checkout">Proceed to Checkout</a><a class="textlink" href="#shop">← Continue Shopping</a></aside></div>`:'<div class="panel empty"><h2>Your cart is empty</h2><p>Add jewellery to your cart to continue.</p><a class="primary" href="#shop">Start Shopping</a></div>'}</main>`)}
  function checkout(){const c=cart();if(!c.length){location.hash='cart';return}const rows=c.map(i=>({i,p:state.products.find(p=>p.id===i.productId)})).filter(x=>x.p);const sub=rows.reduce((s,x)=>s+x.p.price*x.i.qty,0);layout(`<main class="container section"><h1>Checkout</h1><div class="checkout-layout"><form class="panel" onsubmit="window.DAS.place(event)"><h2>Delivery Details</h2><div class="formgrid"><label>Full Name<input id="coName" required></label><label>Mobile<input id="coMobile" required pattern="[0-9 +()-]{8,}"></label><label>Email<input id="coEmail" type="email"></label><label>City<input id="coCity" required></label><label>State<input id="coState" required></label><label>PIN Code<input id="coPin" required></label></div><label>Full Address<textarea id="coAddress" required></textarea></label><h2>Payment</h2><div class="payment-options"><label><input type="radio" name="payment" value="Cash on Delivery" checked> Cash on Delivery</label><label><input type="radio" name="payment" value="UPI"> UPI</label><label><input type="radio" name="payment" value="Card"> Card</label></div><div class="coupon"><input id="couponCode" placeholder="Coupon code"><button type="button" class="outline" onclick="window.DAS.applyCoupon()">Apply</button><span id="couponMsg"></span></div><button class="primary big full" type="submit">Place Order</button></form><aside class="panel summary"><h2>Your Order</h2>${rows.map(x=>`<p>${esc(x.p.name)} × ${x.i.qty}<b>${money(x.p.price*x.i.qty)}</b></p>`).join('')}<hr><p>Subtotal <b id="coSub">${money(sub)}</b></p><p>Delivery <b id="coShip">${sub>=state.settings.freeShippingAbove?'FREE':money(state.settings.shippingCharge)}</b></p><p>Discount <b id="coDisc">₹0</b></p><h2>Total <b id="coTotal">${money(sub+(sub>=state.settings.freeShippingAbove?0:state.settings.shippingCharge))}</b></h2></aside></div></main>`)}
  function offers(){layout(`<main class="container section"><span class="eyebrow">SAVE MORE</span><h1>Offers & Discounts</h1><div class="offer-grid">${state.coupons.filter(c=>c.active!==false).map(c=>`<div class="panel coupon-card"><span class="coupon-label">COUPON</span><h2>${esc(c.code)}</h2><p>${c.type==='percent'?c.value+'% off':money(c.value)+' off'} on orders above ${money(c.minPurchase)}</p><button class="outline" onclick="navigator.clipboard?.writeText('${esc(c.code)}');alert('Coupon copied: ${esc(c.code)}')">Copy Code</button></div>`).join('')}</div><h2 class="section-title">Offer Products</h2><div class="product-grid">${activeProducts().filter(p=>p.discount>=20).map(productCard).join('')}</div></main>`)}
  function wishlist(){const ids=wish();const ps=activeProducts().filter(p=>ids.includes(p.id));layout(`<main class="container section"><span class="eyebrow">SAVED ITEMS</span><h1>Wishlist</h1>${ps.length?`<div class="product-grid">${ps.map(productCard).join('')}</div>`:'<div class="panel empty"><h2>Your wishlist is empty</h2><a class="primary" href="#shop">Browse Jewellery</a></div>'}`)}
  function account(){layout(`<main class="container section"><span class="eyebrow">MY DAS</span><h1>My Account</h1><div class="account-grid"><div class="panel"><h2>Profile</h2><p>Manage your customer details and delivery information.</p><button class="outline" onclick="window.DAS.saveProfile()">Edit Profile</button></div><div class="panel"><h2>My Orders</h2><p>${state.orders.length} order(s) saved on this browser.</p><a class="primary" href="#orders">View Orders</a></div><div class="panel"><h2>Wishlist</h2><p>${wish().length} saved item(s).</p><a class="primary" href="#wishlist">Open Wishlist</a></div><div class="panel"><h2>Track Order</h2><p>Track an order using Order ID and mobile.</p><button class="outline" onclick="window.DAS.trackPrompt()">Track Order</button></div><div class="panel"><h2>Help & Support</h2><p>${esc(state.settings.contactNumber)}</p><p>${esc(state.settings.email)}</p></div></div></main>`)}
  function orders(){layout(`<main class="container section"><span class="eyebrow">ORDER HISTORY</span><h1>My Orders</h1>${state.orders.length?state.orders.slice().reverse().map(o=>`<div class="panel order-card"><div><b>${esc(o.id)}</b><p>${esc(o.createdAt)} · ${money(o.amount)}</p></div><span class="status">${esc(o.status)}</span><button class="outline" onclick="window.DAS.track('${o.id}')">Track</button></div>`).join(''):'<div class="panel empty"><h2>No orders yet</h2><a class="primary" href="#shop">Shop Now</a></div>'}</main>`)}
  function success(id){const o=state.orders.find(x=>x.id===id);if(!o)return notFound();layout(`<main class="container section"><div class="panel success"><div class="success-icon">✓</div><h1>Order Placed Successfully</h1><p>Thank you, ${esc(o.customer)}.</p><div class="success-grid"><div><span>Order ID</span><b>${esc(o.id)}</b></div><div><span>Amount</span><b>${money(o.amount)}</b></div><div><span>Date</span><b>${esc(o.createdAt)}</b></div></div><a class="primary" href="#track/${encodeURIComponent(o.id)}">Track Order</a><a class="outline" href="#shop">Continue Shopping</a></div></main>`)}
  function track(id){const o=state.orders.find(x=>x.id===id);if(!o){alert('Order not found on this browser.');return}const statuses=['Order Received','Confirmed','Processing','Packed','Shipped','Out for Delivery','Delivered'];const n=statuses.indexOf(o.status);layout(`<main class="container section"><div class="panel"><span class="eyebrow">LIVE STATUS</span><h1>Track ${esc(o.id)}</h1><p>${esc(o.customer)} · ${money(o.amount)}</p><div class="timeline">${statuses.map((s,i)=>`<div class="timeline-step ${i<=n?'done':''}"><span>${i+1}</span><div><b>${s}</b><small>${i<n?'Completed':i===n?'Current status':''}</small></div></div>`).join('')}</div><div class="track-actions"><a class="outline" href="#orders">View Orders</a><a class="primary" href="#shop">Continue Shopping</a></div></div></main>`)}
  function trackPrompt(){const id=prompt('Enter Order ID');if(id)location.hash='track/'+encodeURIComponent(id.trim())}
  function notFound(){layout('<main class="container section"><div class="panel empty"><h1>Page not found</h1><a class="primary" href="#home">Go Home</a></div></main>')}
  function add(id,q=1){const p=state.products.find(x=>x.id===id);if(!p||p.stock<=0)return alert('This product is out of stock.');q=Math.max(1,Math.min(Number(q)||1,p.stock));const c=cart();const i=c.find(x=>x.productId===id);if(i)i.qty=Math.min(p.stock,i.qty+q);else c.push({productId:id,qty:q});setCart(c);updateCount();toast('Added to cart');}
  function buy(id){add(id,1);location.hash='checkout'}
  function change(id,d){const c=cart(),i=c.find(x=>x.productId===id),p=state.products.find(x=>x.id===id);if(!i)return;i.qty=Math.max(1,Math.min(p.stock,i.qty+d));setCart(c);cartPage()}
  function remove(id){setCart(cart().filter(x=>x.productId!==id));cartPage()}
  function wishToggle(id){const w=wish();setWish(w.includes(id)?w.filter(x=>x!==id):w.concat(id));toast(w.includes(id)?'Removed from wishlist':'Added to wishlist');route()}
  function applyCoupon(){const code=(document.getElementById('couponCode')?.value||'').trim().toUpperCase();const c=state.coupons.find(x=>x.code===code&&x.active!==false);const rows=cart().map(i=>({i,p:state.products.find(p=>p.id===i.productId)})).filter(x=>x.p);const sub=rows.reduce((s,x)=>s+x.p.price*x.i.qty,0);const msg=document.getElementById('couponMsg');if(!c){msg.textContent=' Invalid coupon';msg.className='bad';return}if(sub<c.minPurchase){msg.textContent=' Minimum '+money(c.minPurchase);msg.className='bad';return}const disc=c.type==='percent'?Math.round(sub*c.value/100):c.value;localStorage.setItem('das-coupon',JSON.stringify({code,discount:disc}));msg.textContent=' Applied '+code;msg.className='good';const ship=sub>=state.settings.freeShippingAbove?0:state.settings.shippingCharge;document.getElementById('coDisc').textContent='-'+money(disc);document.getElementById('coTotal').textContent=money(Math.max(0,sub+ship-disc))}
  function place(e){e.preventDefault();const rows=cart().map(i=>({i,p:state.products.find(p=>p.id===i.productId)})).filter(x=>x.p);if(!rows.length)return;for(const x of rows)if(x.i.qty>x.p.stock)return alert('Stock changed for '+x.p.name);const sub=rows.reduce((s,x)=>s+x.p.price*x.i.qty,0);const ship=sub>=state.settings.freeShippingAbove?0:state.settings.shippingCharge;const cp=JSON.parse(localStorage.getItem('das-coupon')||'null');const disc=cp?.discount||0;const o={id:'ORD-'+Date.now().toString().slice(-8),customer:document.getElementById('coName').value.trim(),mobile:document.getElementById('coMobile').value.trim(),email:document.getElementById('coEmail').value.trim(),city:document.getElementById('coCity').value.trim(),state:document.getElementById('coState').value.trim(),pin:document.getElementById('coPin').value.trim(),address:document.getElementById('coAddress').value.trim(),payment:document.querySelector('input[name="payment"]:checked').value,items:rows.map(x=>({productId:x.p.id,qty:x.i.qty,price:x.p.price,name:x.p.name})),subtotal:sub,shipping:ship,discount:disc,amount:Math.max(0,sub+ship-disc),status:'Order Received',createdAt:new Date().toLocaleString('en-IN'),history:[{status:'Order Received',at:new Date().toLocaleString('en-IN')}]};state.orders.push(o);let cu=state.customers.find(x=>x.mobile===o.mobile);if(!cu){cu={id:'C-'+Date.now(),name:o.customer,mobile:o.mobile,email:o.email,totalOrders:0,totalPurchase:0,lastOrder:o.createdAt,status:'Active'};state.customers.push(cu)}cu.totalOrders++;cu.totalPurchase+=o.amount;cu.lastOrder=o.createdAt;rows.forEach(x=>x.p.stock-=x.i.qty);save();setCart([]);localStorage.removeItem('das-coupon');location.hash='success/'+encodeURIComponent(o.id)}
  function saveProfile(){const name=prompt('Name');if(name){localStorage.setItem('das-profile',JSON.stringify({name}));toast('Profile saved')}}
  function search(){const q=document.getElementById('searchBox')?.value.trim()||'';location.hash='search/'+encodeURIComponent(q)}
  function cat(c){location.hash='cat/'+encodeURIComponent(c)}
  function qty(d){const i=document.getElementById('detailQty');if(i)i.value=Math.max(1,Math.min(Number(i.max)||99,(Number(i.value)||1)+d))}
  function theme(){const t=localStorage.getItem('das-theme')==='dark'?'light':'dark';localStorage.setItem('das-theme',t);document.documentElement.dataset.theme=t}
  function toggleMenu(){document.getElementById('mainNav')?.classList.toggle('open')}
  function updateCount(){const x=document.getElementById('cartCount');if(x)x.textContent=countCart()}
  function toast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
  function route(){const raw=location.hash.slice(1)||'home',parts=raw.split('/'),key=decodeURIComponent(parts[0]||'home'),arg=decodeURIComponent(parts.slice(1).join('/')||'');try{if(key==='home')home();else if(key==='shop')shop();else if(key==='cat')shop(arg);else if(key==='search')shop('All',arg);else if(key==='product')product(arg);else if(key==='cart')cartPage();else if(key==='checkout')checkout();else if(key==='offers-page'||key==='offers')offers();else if(key==='wishlist')wishlist();else if(key==='account')account();else if(key==='orders')orders();else if(key==='success')success(arg);else if(key==='track')track(arg);else notFound()}catch(e){console.error(e);notFound()}}
  window.DAS={add,buy,wish:wishToggle,change,remove,applyCoupon,place,search,cat,qty,theme,toggleMenu,track,trackPrompt,saveProfile};
  addEventListener('hashchange',route);addEventListener('storage',()=>{state=load();route()});route();
})();
