const BASE='./';
const seed={
 categories:['Gold Jewellery','Silver Jewellery','Ring','Earrings','Necklace','Bangles','Bracelet','Anklet','Mangalsutra','Gift','Offers'],
 products:[
  {id:'P001',name:'Gold Plated Necklace',category:'Necklace',price:1099,oldPrice:1999,discount:45,stock:15,sku:'DN-001',material:'Gold Plated',purity:'18K Finish',weight:'18g',size:'Free Size',description:'Elegant statement necklace for festive and wedding occasions.',image:'./assets/jewellery/gold-necklace-01.jpg',featured:true,rating:4.8,active:true},
  {id:'P002',name:'Classic Gold Ring',category:'Ring',price:799,oldPrice:1299,discount:38,stock:22,sku:'DR-002',material:'Gold Plated',purity:'18K Finish',weight:'5g',size:'Adjustable',description:'Minimal everyday ring with a classic finish.',image:'./assets/jewellery/gold-ring-01.jpg',featured:true,rating:4.7,active:true},
  {id:'P003',name:'Designer Earrings',category:'Earrings',price:649,oldPrice:999,discount:35,stock:30,sku:'DE-003',material:'Gold Plated',purity:'18K Finish',weight:'8g',size:'Standard',description:'Lightweight earrings for festive and daily styling.',image:'./assets/jewellery/earrings-01.jpg',featured:true,rating:4.6,active:true},
  {id:'P004',name:'Elegant Bangles Set',category:'Bangles',price:1299,oldPrice:1999,discount:35,stock:12,sku:'DB-004',material:'Gold Plated',purity:'18K Finish',weight:'25g',size:'2.4–2.8',description:'A versatile bangle set for celebrations.',image:'./assets/jewellery/bangles-01.jpg',featured:true,rating:4.8,active:true},
  {id:'P005',name:'Daily Wear Bracelet',category:'Bracelet',price:899,oldPrice:1399,discount:36,stock:18,sku:'DBR-005',material:'Gold Plated',purity:'18K Finish',weight:'12g',size:'Adjustable',description:'Simple bracelet designed for everyday elegance.',image:'./assets/jewellery/bracelet-01.jpg',featured:false,rating:4.5,active:true},
  {id:'P006',name:'Traditional Mangalsutra',category:'Mangalsutra',price:1499,oldPrice:2199,discount:32,stock:9,sku:'DM-006',material:'Gold Plated',purity:'18K Finish',weight:'20g',size:'18 inch',description:'Traditional styling with a contemporary finish.',image:'./assets/jewellery/mangalsutra-01.jpg',featured:true,rating:4.9,active:true},
  {id:'P007',name:'Classic Anklet Pair',category:'Anklet',price:999,oldPrice:1499,discount:33,stock:14,sku:'DA-007',material:'Silver Plated',purity:'92.5 Finish',weight:'22g',size:'Adjustable',description:'Elegant anklet pair with a comfortable fit.',image:'./assets/jewellery/anklet-01.jpg',featured:false,rating:4.4,active:true},
  {id:'P008',name:'Festive Gift Set',category:'Gift',price:1599,oldPrice:2499,discount:36,stock:8,sku:'DG-008',material:'Gold Plated',purity:'18K Finish',weight:'30g',size:'Standard',description:'A ready-to-gift jewellery set for special occasions.',image:'./assets/jewellery/gift-set-01.jpg',featured:true,rating:4.8,active:true}
 ],
 banners:[{id:'B001',title:'Luxury In Every Detail',image:'./assets/banners/banner-01.jpg',active:true},{id:'B002',title:'Festive Collection',image:'./assets/banners/banner-02.jpg',active:true},{id:'B003',title:'Everyday Elegance',image:'./assets/banners/banner-03.jpg',active:true}],
 coupons:[{code:'WELCOME10',type:'percent',value:10,minPurchase:500,active:true},{code:'SAVE500',type:'fixed',value:500,minPurchase:2500,active:true}],
 orders:[],reviews:[],settings:{websiteName:'DAS ENTERPRISES',contactNumber:'',email:'',address:'',shippingCharge:100,returnPolicy:'7 Days Return'}
};
const clone=o=>JSON.parse(JSON.stringify(o));
let db=JSON.parse(localStorage.getItem('das_db_v2')||'null')||clone(seed);let cart=JSON.parse(localStorage.getItem('das_cart')||'[]');let wish=JSON.parse(localStorage.getItem('das_wish')||'[]');let theme=localStorage.getItem('das_theme')||'light';
function persist(){localStorage.setItem('das_db_v2',JSON.stringify(db));localStorage.setItem('das_cart',JSON.stringify(cart));localStorage.setItem('das_wish',JSON.stringify(wish));localStorage.setItem('das_theme',theme);document.body.classList.toggle('dark',theme==='dark')}
persist();const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');const app=document.getElementById('app');
function header(){return `<header class="top"><div class="wrap bar"><a href="#home"><img class="logo" src="./assets/logo/das-logo.jpg"></a><span class="brand">DAS ENTERPRISES</span><div class="search"><input id="q" placeholder="Search jewellery" onkeydown="if(event.key==='Enter')doSearch()"><button onclick="doSearch()">🔍</button></div><nav class="nav"><a href="#home">Home</a><a href="#shop">Categories</a><a href="#offers">Offers</a><a href="#wishlist">♥</a><a href="#account">👤</a><a href="#cart">🛒 ${cart.reduce((a,x)=>a+x.qty,0)}</a><button class="iconbtn" onclick="toggleTheme()">☾/☀</button><a href="./admin/">Admin</a></nav></div></header>`}
function footer(){return `<footer class="footer"><div class="wrap"><b>${db.settings.websiteName}</b><p>Jewellery for a Better Tomorrow</p><p>Premium designs • Secure ordering • 7 Days Return</p><p><a href="./admin/">Admin Dashboard</a></p></div></footer>`}
function toast(t){const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
function productCard(p){return `<article class="card"><a href="#product/${p.id}"><img src="${p.image}" alt="${p.name}"></a><div class="p"><b>${p.name}</b><div><span class="price">${money(p.price)}</span><span class="old">${money(p.oldPrice)}</span></div><small>★ ${p.rating||4.5} • ${p.stock} in stock</small><div class="actions"><button class="ghost" onclick="event.preventDefault();toggleWish('${p.id}')">${wish.includes(p.id)?'♥':'♡'}</button><button class="btn" onclick="event.preventDefault();addToCart('${p.id}')">Add to Cart</button></div></div></article>`}
function categories(){return db.categories.map(c=>`<button class="chip" onclick="location.hash='cat/${encodeURIComponent(c)}'">${c}</button>`).join('')}
function home(){const b=db.banners.find(x=>x.active)||db.banners[0], p=db.products.filter(x=>x.active);app.innerHTML=header()+`<main class="wrap"><section class="hero"><img src="${b.image}"><div class="heroText"><h1>Luxury In Every Detail</h1><p>Premium jewellery designed to make every moment memorable.</p><button class="btn" onclick="location.hash='shop'">Shop Now</button></div></section><section class="section"><h2>Shop by Category</h2><div class="chips">${categories()}</div></section><section class="section"><h2>Featured Jewellery</h2><div class="grid">${p.filter(x=>x.featured).map(productCard).join('')}</div></section><section id="offers" class="section"><h2>Special Offers</h2><div class="grid">${p.filter(x=>x.discount>=25).map(productCard).join('')}</div></section></main>${footer()}`}
function shop(category='All',q=''){let p=db.products.filter(x=>x.active);if(category!=='All')p=p.filter(x=>x.category===category);if(q)p=p.filter(x=>(x.name+' '+x.category+' '+x.description).toLowerCase().includes(q.toLowerCase()));app.innerHTML=header()+`<main class="wrap section"><h2>Jewellery Collection</h2><div class="chips"><button class="chip" onclick="location.hash='shop'">All</button>${categories()}</div><p>${q?`Search results for <b>${q}</b>`:category!=='All'?`Category: <b>${category}</b>`:''}</p><div class="grid">${p.length?p.map(productCard).join(''):'<div class="panel empty">No products found.</div>'}</div></main>${footer()}`}
function product(id){const p=db.products.find(x=>x.id===id);if(!p)return shop();app.innerHTML=header()+`<main class="wrap section"><button class="ghost" onclick="history.back()">← Back</button><div class="two" style="margin-top:15px"><div class="panel"><img src="${p.image}" style="width:100%;border-radius:12px" alt="${p.name}"></div><div class="panel"><span class="badge">${p.category}</span><h1>${p.name}</h1><div><span class="price">${money(p.price)}</span><span class="old">${money(p.oldPrice)}</span></div><p>★ ${p.rating} • ${p.stock} in stock • ${p.discount}% OFF</p><hr><p>${p.description}</p><p><b>Material:</b> ${p.material}<br><b>Purity:</b> ${p.purity}<br><b>Weight:</b> ${p.weight}<br><b>Size:</b> ${p.size}</p><div class="qty"><button onclick="document.getElementById('pq').stepDown()">−</button><input id="pq" type="number" value="1" min="1" max="${p.stock}" style="width:65px"><button onclick="document.getElementById('pq').stepUp()">+</button></div><div class="actions"><button class="btn" onclick="addToCart('${p.id}',+pq.value)">Add to Cart</button><button class="btn" onclick="addToCart('${p.id}',+pq.value);location.hash='checkout'">Buy Now</button><button class="ghost" onclick="toggleWish('${p.id}')">${wish.includes(p.id)?'♥':'♡'} Wishlist</button></div><p>Delivery: 3–7 Days • Return: 7 Days</p></div></div></main>${footer()}`}
function addToCart(id,qty=1){const p=db.products.find(x=>x.id===id);if(!p||p.stock<qty)return toast('Insufficient stock');const i=cart.find(x=>x.productId===id);if(i)i.qty=Math.min(p.stock,i.qty+qty);else cart.push({productId:id,qty});persist();toast('Added to cart');render()}
function toggleWish(id){wish=wish.includes(id)?wish.filter(x=>x!==id):[...wish,id];persist();toast(wish.includes(id)?'Added to wishlist':'Removed from wishlist');render()}
function cartPage(){const rows=cart.map(i=>({i,p:db.products.find(p=>p.id===i.productId)})).filter(x=>x.p);const sub=rows.reduce((s,x)=>s+x.p.price*x.i.qty,0),ship=sub>=1500||!sub?0:db.settings.shippingCharge;app.innerHTML=header()+`<main class="wrap section"><h2>Your Cart</h2><div class="two"><div class="panel">${rows.length?rows.map(x=>`<div class="cartrow"><img src="${x.p.image}"><div><b>${x.p.name}</b><p>${money(x.p.price)} × ${x.i.qty}</p><div class="qty"><button onclick="changeQty('${x.p.id}',-1)">−</button><span>${x.i.qty}</span><button onclick="changeQty('${x.p.id}',1)">+</button><button class="ghost" onclick="removeCart('${x.p.id}')">🗑</button></div></div><b>${money(x.p.price*x.i.qty)}</b></div>`).join(''):'<div class="empty">Your cart is empty.<br><br><button class="btn" onclick="location.hash='shop'">Continue Shopping</button></div>'}</div><div class="panel"><h3>Order Summary</h3><p>Subtotal <span style="float:right">${money(sub)}</span></p><p>Delivery <span style="float:right">${money(ship)}</span></p><hr><h3>Total <span style="float:right">${money(sub+ship)}</span></h3><button class="btn" style="width:100%" ${rows.length?'':'disabled'} onclick="location.hash='checkout'">Proceed to Checkout</button></div></div></main>${footer()}`}
function changeQty(id,d){const i=cart.find(x=>x.productId===id),p=db.products.find(x=>x.id===id);if(i){i.qty=Math.max(1,Math.min(p.stock,i.qty+d));persist();cartPage()}}function removeCart(id){cart=cart.filter(x=>x.productId!==id);persist();cartPage()}
function checkout(){const rows=cart.map(i=>({i,p:db.products.find(p=>p.id===i.productId)})).filter(x=>x.p);if(!rows.length)return cartPage();const sub=rows.reduce((s,x)=>s+x.p.price*x.i.qty,0),ship=sub>=1500?0:db.settings.shippingCharge;app.innerHTML=header()+`<main class="wrap section"><h2>Checkout</h2><div class="two"><div class="panel"><div class="field"><label>Full Name</label><input id="name" required></div><div class="field"><label>Mobile</label><input id="mobile" required></div><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>Address</label><textarea id="address" required></textarea></div><div class="field"><label>City</label><input id="city"></div><div class="field"><label>State</label><input id="state"></div><div class="field"><label>PIN</label><input id="pin"></div><div class="field"><label>Payment</label><select id="payment"><option>Cash on Delivery</option><option>UPI</option><option>Card</option></select></div><div class="field"><label>Coupon</label><div><input id="coupon" placeholder="WELCOME10"> <button class="ghost" onclick="applyCoupon()">Apply</button></div><span id="cm"></span></div></div><div class="panel"><h3>Order Summary</h3>${rows.map(x=>`<p>${x.p.name} × ${x.i.qty}<span style="float:right">${money(x.p.price*x.i.qty)}</span></p>`).join('')}<hr><p>Shipping <span style="float:right">${money(ship)}</span></p><h3>Total <span id="tot" style="float:right">${money(sub+ship)}</span></h3><button class="btn" style="width:100%" onclick="placeOrder()">Place Order</button></div></div></main>${footer()}`}
let discount=0;function applyCoupon(){const c=db.coupons.find(x=>x.active&&x.code.toUpperCase()===(coupon.value||'').toUpperCase());const rows=cart.map(i=>({i,p:db.products.find(p=>p.id===i.productId)}));const sub=rows.reduce((s,x)=>s+x.p.price*x.i.qty,0);if(!c)return cm.textContent=' Invalid coupon';if(sub<c.minPurchase)return cm.textContent=' Minimum purchase '+money(c.minPurchase);discount=c.type==='percent'?Math.round(sub*c.value/100):c.value;cm.textContent=` Applied ${c.code} (-${money(discount)})`;const ship=sub>=1500?0:db.settings.shippingCharge;tot.textContent=money(Math.max(0,sub+ship-discount))}
function placeOrder(){const required=[name,mobile,address];if(required.some(x=>!x.value.trim()))return toast('Please fill required fields');const rows=cart.map(i=>({i,p:db.products.find(p=>p.id===i.productId)}));const sub=rows.reduce((s,x)=>s+x.p.price*x.i.qty,0),ship=sub>=1500?0:db.settings.shippingCharge,total=Math.max(0,sub+ship-discount);const id='ORD'+Date.now().toString().slice(-8);rows.forEach(x=>x.p.stock-=x.i.qty);db.orders.unshift({id,customer:name.value,mobile:mobile.value,email:email.value,address:address.value,city:city.value,state:state.value,pin:pin.value,payment:payment.value,items:rows.map(x=>({productId:x.p.id,name:x.p.name,price:x.p.price,qty:x.i.qty})),subtotal:sub,shipping:ship,discount,amount:total,status:'Order Received',createdAt:new Date().toISOString()});persist();cart=[];discount=0;persist();location.hash='success/'+id}
function success(id){const o=db.orders.find(x=>x.id===id);if(!o)return home();app.innerHTML=header()+`<main class="wrap section"><div class="panel" style="text-align:center"><div style="font-size:60px">✓</div><h1>Order Placed Successfully</h1><p>Order ID: <b>${o.id}</b></p><p>Amount: <b>${money(o.amount)}</b></p><p>${new Date(o.createdAt).toLocaleString('en-IN')}</p><button class="btn" onclick="location.hash='track/${o.id}'">Track Order</button> <button class="ghost" onclick="location.hash='shop'">Continue Shopping</button></div></main>${footer()}`}
function track(id){if(!id){id=prompt('Order ID');if(!id)return}const o=db.orders.find(x=>x.id===id);if(!o)return toast('Order not found');const ss=['Order Received','Confirmed','Processing','Packed','Shipped','Out for Delivery','Delivered'];const n=ss.indexOf(o.status);app.innerHTML=header()+`<main class="wrap section"><div class="panel"><h2>Track Order ${o.id}</h2><p>${o.customer} • ${money(o.amount)}</p><div class="track">${ss.map((s,i)=>`<span class="step ${i<=n?'done':''}">${i+1}. ${s}</span>`).join('')}</div><h3 style="margin-top:28px">Items</h3>${o.items.map(x=>`<p>${x.name} × ${x.qty} <span style="float:right">${money(x.price*x.qty)}</span></p>`).join('')}</div></main>${footer()}`}
function wishlist(){const p=wish.map(id=>db.products.find(x=>x.id===id)).filter(Boolean);app.innerHTML=header()+`<main class="wrap section"><h2>Wishlist ♥</h2><div class="grid">${p.length?p.map(productCard).join(''):'<div class="panel empty">Your wishlist is empty.</div>'}</div></main>${footer()}`}
function account(){app.innerHTML=header()+`<main class="wrap section"><h2>My Account</h2><div class="grid"><div class="panel"><h3>My Orders</h3><p>${db.orders.length} local order(s)</p><button class="btn" onclick="location.hash='track'">Track Order</button></div><div class="panel"><h3>Wishlist</h3><p>${wish.length} saved product(s)</p><button class="btn" onclick="location.hash='wishlist'">Open Wishlist</button></div><div class="panel"><h3>Help & Support</h3><p>${db.settings.contactNumber||'Contact details will appear here.'}</p></div><div class="panel"><h3>Admin</h3><a class="btn" style="display:inline-block" href="./admin/">Open Admin Dashboard</a></div></div></main>${footer()}`}
function doSearch(){location.hash='search/'+encodeURIComponent(document.getElementById('q').value||'')}
function toggleTheme(){theme=theme==='dark'?'light':'dark';persist();render()}
function render(){const [r,a]=location.hash.slice(1).split('/');const v=decodeURIComponent(a||'');if(r==='home'||!r)return home();if(r==='shop')return shop();if(r==='cat')return shop(v);if(r==='search')return shop('All',v);if(r==='product')return product(v);if(r==='cart')return cartPage();if(r==='checkout')return checkout();if(r==='success')return success(v);if(r==='track')return track(v);if(r==='wishlist')return wishlist();if(r==='account')return account();return home()}
addEventListener('hashchange',render);render();
