const $=s=>document.querySelector(s),money=n=>"₹"+Number(n||0).toLocaleString("en-IN"),S={cart:JSON.parse(localStorage.cart||"[]"),wish:JSON.parse(localStorage.wish||"[]"),theme:localStorage.theme||"light",ps:[]};document.documentElement.dataset.theme=S.theme;
async function api(u,o={}){let r=await fetch(u,o),d=await r.json();if(!r.ok)throw Error(d.error||"Error");return d}
function save(){localStorage.cart=JSON.stringify(S.cart);localStorage.wish=JSON.stringify(S.wish)}
function header(){return `<div class=top><div class="wrap bar"><a href="#home"><img class=logo src=/assets/logo/das-logo.jpg></a><div class=search><input id=q placeholder="Search jewellery"><button onclick="search()">🔍</button></div><div class=nav><a href="#home">Home</a><a href="#shop">Categories</a><a href="#offers">Offers</a><a href="#account">👤</a><a href="#cart">🛒 ${S.cart.reduce((a,x)=>a+x.qty,0)}</a><button class=toggle onclick="theme()">☾/☀</button><a href="/admin">Admin</a></div></div></div>`}
function footer(){return `<footer class=footer><div class=wrap><b>DAS ENTERPRISES</b><p>Jewellery for a Better Tomorrow</p><p>Premium designs • Secure ordering • 7 Days Return</p></div></footer>`}
function pc(p){return `<div class=card><a href="#product/${p.id}"><img src="${p.image}"></a><div class=p><b>${p.name}</b><div><span class=price>${money(p.price)}</span><span class=old>${money(p.oldPrice)}</span></div><small>★ ${p.rating||4.5} • ${p.stock} in stock</small><div class=actions><button class=ghost onclick="event.preventDefault();wish('${p.id}')">♥</button><button class=btn onclick="event.preventDefault();add('${p.id}')">Add to Cart</button></div></div></div>`}
async function home(){let b=await api("/api/banners"),p=await api("/api/products");S.ps=p;let c=await api("/api/categories");$("#app").innerHTML=header()+`<main class=wrap><div class=hero><img src="${b[0]?.image||'/assets/banners/banner-01.jpg'}"><div class=heroText><h1>Luxury In Every Detail</h1><p>Premium jewellery designed to make every moment memorable.</p><button class=btn onclick="location.hash='shop'">Shop Now</button></div></div><section class=section><h2>Shop by Category</h2><div class=chips><button class=chip onclick="cat('All')">All</button>${c.map(x=>`<button class=chip onclick="cat('${x}')">${x}</button>`).join("")}</div></section><section class=section><h2>Featured Jewellery</h2><div class=grid>${p.filter(x=>x.featured).map(pc).join("")}</div></section><section id=offers class=section><h2>Special Offers</h2><div class=grid>${p.filter(x=>x.discount>=25).map(pc).join("")}</div></section></main>${footer()}`}
async function shop(c="All",q=""){let p=await api(`/api/products?category=${encodeURIComponent(c)}&q=${encodeURIComponent(q)}`);S.ps=p;$("#app").innerHTML=header()+`<main class="wrap section"><h2>Jewellery Collection</h2><div class=chips><button class=chip onclick="cat('All')">All</button>${(await api("/api/categories")).map(x=>`<button class=chip onclick="cat('${x}')">${x}</button>`).join("")}</div><p>${q?"Search: "+q:""}</p><div class=grid>${p.map(pc).join("")}</div></main>${footer()}`}
function cat(c){location.hash="cat/"+encodeURIComponent(c)}
function search(){location.hash="search/"+encodeURIComponent($("#q").value||"")}
async function product(id){let p=await api("/api/products/"+id);S.ps.push(p);$("#app").innerHTML=header()+`<main class="wrap section"><button class=ghost onclick="history.back()">← Back</button><div class=two style="margin-top:15px"><div class=panel><img src="${p.image}" style="width:100%;border-radius:12px"></div><div class=panel><h1>${p.name}</h1><div class=price>${money(p.price)} <span class=old>${money(p.oldPrice)}</span></div><p>★ ${p.rating} • ${p.stock} in stock • ${p.discount}% OFF</p><hr><p>${p.description}</p><p><b>Material:</b> ${p.material}<br><b>Purity:</b> ${p.purity}<br><b>Weight:</b> ${p.weight}<br><b>Size:</b> ${p.size}</p><div class=qty><button onclick="pq.stepDown()">−</button><input id=pq type=number value=1 min=1 max=${p.stock} style="width:55px"><button onclick="pq.stepUp()">+</button></div><div class=actions><button class=btn onclick="add('${p.id}',+pq.value)">Add to Cart</button><button class=btn onclick="add('${p.id}',+pq.value);location.hash='checkout'">Buy Now</button><button class=ghost onclick="wish('${p.id}')">♥</button></div><p>Delivery: 3–7 Days • Return: 7 Days</p></div></div></main>${footer()}`}
function add(id,q=1){let i=S.cart.find(x=>x.productId===id);i?i.qty+=q:S.cart.push({productId:id,qty:q});save();alert("Added to cart")}
function wish(id){S.wish=S.wish.includes(id)?S.wish.filter(x=>x!==id):[...S.wish,id];save()}
async function cart(){let a=S.cart.map(i=>({...i,p:S.ps.find(p=>p.id===i.productId)})).filter(x=>x.p);let sub=a.reduce((s,x)=>s+x.p.price*x.qty,0);$("#app").innerHTML=header()+`<main class="wrap section"><h2>Your Cart</h2><div class=two><div class=panel>${a.length?a.map(x=>`<div class=cartrow><img src=${x.p.image}><div><b>${x.p.name}</b><p>${money(x.p.price)} × ${x.qty}</p><div class=qty><button onclick="chg('${x.p.id}',-1)">−</button><span>${x.qty}</span><button onclick="chg('${x.p.id}',1)">+</button><button class=ghost onclick="rm('${x.p.id}')">🗑</button></div></div><b>${money(x.p.price*x.qty)}</b></div>`).join(""):"<p>Your cart is empty.</p>"}</div><div class=panel><h3>Order Summary</h3><p>Subtotal <span style=float:right>${money(sub)}</span></p><p>Delivery <span style=float:right>${money(sub>=1500||!sub?0:100)}</span></p><hr><h3>Total <span style=float:right>${money(sub+(sub>=1500||!sub?0:100))}</span></h3><button class=btn style="width:100%" onclick="location.hash='checkout'">Proceed to Checkout</button></div></div></main>${footer()}`}
function chg(id,d){let i=S.cart.find(x=>x.productId===id);i.qty=Math.max(1,i.qty+d);save();cart()}function rm(id){S.cart=S.cart.filter(x=>x.productId!==id);save();cart()}
let disc=0;async function checkout(){let a=S.cart.map(i=>({...i,p:S.ps.find(p=>p.id===i.productId)})).filter(x=>x.p),sub=a.reduce((s,x)=>s+x.p.price*x.qty,0);$("#app").innerHTML=header()+`<main class="wrap section"><h2>Checkout</h2><div class=two><div class=panel><div class=field><label>Full Name</label><input id=name></div><div class=field><label>Mobile</label><input id=mobile></div><div class=field><label>Email</label><input id=email></div><div class=field><label>Address</label><textarea id=address></textarea></div><div class=field><label>Payment</label><select id=payment><option>Cash on Delivery</option><option>UPI</option><option>Card</option></select></div><div class=field><label>Coupon</label><input id=coupon placeholder=WELCOME10><button class=ghost onclick=applyCoupon()>Apply Coupon</button><span id=cm></span></div></div><div class=panel><h3>Order Summary</h3>${a.map(x=>`<p>${x.p.name} × ${x.qty}<span style=float:right>${money(x.p.price*x.qty)}</span></p>`).join("")}<hr><h3>Total <span id=tot style=float:right>${money(sub+(sub>=1500?0:100))}</span></h3><button class=btn style="width:100%" onclick=place()>Place Order</button></div></div></main>${footer()}`}
async function applyCoupon(){try{let c=await api("/api/coupons/"+coupon.value.toUpperCase()),a=S.cart.map(i=>({...i,p:S.ps.find(p=>p.id===i.productId)})),sub=a.reduce((s,x)=>s+x.p.price*x.qty,0);if(sub<c.minPurchase)throw Error("Minimum "+money(c.minPurchase));disc=c.type==="percent"?Math.round(sub*c.value/100):c.value;cm.textContent=" Applied "+c.code;tot.textContent=money(Math.max(0,sub+(sub>=1500?0:100)-disc))}catch(e){cm.textContent=" "+e.message}}
async function place(){try{let o=await api("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer:name.value,mobile:mobile.value,email:email.value,address:address.value,payment:payment.value,discount:disc,items:S.cart})});S.cart=[];save();location.hash="success/"+o.id}catch(e){alert(e.message)}}
async function success(id){let o=await api("/api/orders/track?orderId="+id);$("#app").innerHTML=header()+`<main class="wrap section"><div class=panel style=text-align:center><div style=font-size:60px>✓</div><h1>Order Placed Successfully</h1><p>Order ID: <b>${o.id}</b></p><p>Amount: <b>${money(o.amount)}</b></p><button class=btn onclick="location.hash='track/${o.id}'">Track Order</button> <button class=ghost onclick="location.hash='shop'">Continue Shopping</button></div></main>`}
async function track(id){if(!id){id=prompt("Order ID");if(!id)return}let mobile=prompt("Mobile Number");try{let o=await api(`/api/orders/track?orderId=${encodeURIComponent(id)}&mobile=${encodeURIComponent(mobile||"")}`);let ss=["Order Received","Confirmed","Processing","Packed","Shipped","Out for Delivery","Delivered"],n=ss.indexOf(o.status);$("#app").innerHTML=header()+`<main class="wrap section"><div class=panel><h2>Track Order ${o.id}</h2><p>${o.customer} • ${money(o.amount)}</p><div class=track>${ss.map((s,i)=>`<span class="step ${i<=n?"done":""}">${i+1}. ${s}</span>`).join("")}</div></div></main>`}catch(e){alert(e.message)}}
function account(){$("#app").innerHTML=header()+`<main class="wrap section"><h2>My Account</h2><div class=grid><div class=panel><h3>Profile</h3><p>Customer profile area</p></div><div class=panel><h3>My Orders</h3><button class=btn onclick="track()">Track Order</button></div><div class=panel><h3>Wishlist</h3><button class=btn onclick="location.hash='wishlist'">Open Wishlist</button></div><div class=panel><h3>Help & Support</h3><p>Customer support area</p></div></div></main>${footer()}`}
async function wishlist(){let p=[];for(const id of S.wish)try{p.push(await api("/api/products/"+id))}catch{}$("#app").innerHTML=header()+`<main class="wrap section"><h2>Wishlist ♥</h2><div class=grid>${p.map(pc).join("")}</div></main>${footer()}`}
function theme(){S.theme=S.theme==="dark"?"light":"dark";localStorage.theme=S.theme;document.documentElement.dataset.theme=S.theme}
async function route(){let h=location.hash.slice(1)||"home";if(h==="home")return home();if(h==="shop")return shop();if(h==="cart")return cart();if(h==="checkout")return checkout();if(h==="account")return account();if(h==="wishlist")return wishlist();if(h==="track")return track();if(h.startsWith("track/"))return track(h.split("/")[1]);if(h.startsWith("product/"))return product(h.split("/")[1]);if(h.startsWith("success/"))return success(h.split("/")[1]);if(h.startsWith("cat/"))return shop(decodeURIComponent(h.slice(4)));if(h.startsWith("search/"))return shop("All",decodeURIComponent(h.slice(7)));return home()}
addEventListener("hashchange",route);window.add=add;window.wish=wish;window.cat=cat;window.search=search;window.chg=chg;window.rm=rm;window.applyCoupon=applyCoupon;window.place=place;window.theme=theme;route();